#!/bin/sh
# _                                   
#| |__  ___ _ ____      ___ __ ___  
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_|   ~by nichtgestalt


# SXHKD - Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &


# Activate Polybar
$HOME/.config/polybar/bspwm.sh


# Workspaces
bspc monitor HDMI-A-0 -d "" "" "" "" "" "" "" 


# Gaps and Borders
bspc config border_width           2
bspc config focused_border_color   "#3071db"
bspc config presel_feedback_color  "#3071db"
bspc config normal_border_color    "#222222"

bspc config window_gap             12
bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true


# Window Rules
bspc rule -a Nitrogen              state=floating
bspc rule -a Ristretto             state=floating
bspc rule -a Gpick                 state=floating
bspc rule -a Toolkit               state=floating
bspc rule -a Parole                state=floating


# Other settings
#bspc config focus_follows_pointer  true


# Autostart
setxkbmap de &
nitrogen --restore &
#nitrogen --set-zoom-fill $HOME/.config/bspwm/wallpaper1.jpg &
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
dunst &
unclutter -idle 3 -root &
xset r rate 250 30 &
#bspc desktop -f '^4' &
sleep 0.05
#polybar-msg cmd hide; bspc config top_padding +0
setxkbmap de neo &
