#!/bin/sh
# _                                   
#| |__  ___ _ ____      ___ __ ___  
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_|   ~by nichtgestalt


# SXHKD - Keybindings
pgrep -x sxhkd > /dev/null || sxhkd -d $HOME/.config/sxhkd/prototype-sxhkdrc &


# Activate Polybar
$HOME/.config/polybar/bspwm.sh


# Workspaces
Display=$(xrandr | grep -w 'connected' | awk '{print$1}')	# Set main monitor automatically
bspc monitor $Display -d "1" "2" "3" "4" "5" "6" "7" 		# Set workspace names
bspc monitor HDMI-A-0 -d "" "" "" "" "" "" "" 
#bspc monitor DisplayPort-0 -d "1" "2" "3" "4" "5" 


# Gaps and Borders
bspc config border_width           1
bspc config normal_border_color   "#5c6370"
bspc config focused_border_color  "#3073db"
bspc config presel_feedback_color "#3f444a"

bspc config window_gap             12
bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true


# Window Rules
bspc rule -a Nitrogen              state=floating
bspc rule -a Ristretto             state=floating
bspc rule -a Gpick                 state=floating
bspc rule -a Toolkit               state=floating
bspc rule -a Parole                state=floating



# Autostart
setxkbmap de &
nitrogen  --restore &
xsetroot  -cursor_name left_ptr &
picom     -fc &
#picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
unclutter -idle 2 -root &
#polybar-msg cmd hide; bspc config top_padding +0
#bspc desktop -f '^4' &
sleep 0.05
xset r rate 250 30 &
setxkbmap de neo &
dunst &
