#!/bin/sh
# _                                 
#| |__  ___ _ ____      ___ __ ___  
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_|   ~by nichtgestalt


# SXHKD - Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &


# Configure Monitors
if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
	xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of DP-2
fi


# Polybar
#$HOME/.config/polybar/bspwm.sh


# Workspaces
bspc monitor HDMI-A-0 -d  爵    
bspc monitor DP-1 -d 1 2 3


# Gaps and Borders
bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#51AFEF"
bspc config normal_border_color "#222222"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window Rules
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Gpick state=floating
bspc rule -a Toolkit state=floating
bspc rule -a Ristretto state=floating


# Autostart
setxkbmap de &
nitrogen --restore &
nitrogen --set-zoom-fill $HOME/.config/bspwm/wallpaper1.jpg &
xsetroot -cursor_name left_ptr &
picom -fc --experimental-backends &
ibus exit &
dunst &
unclutter -idle 3 -root &
#bspc desktop -f '^4' &
