[module/menu-apps]
type = custom/menu
expand-right = false

label-open      = 
label-close     = 
label-separator = 
;label-separator = 

format-spacing = 2
format-padding = 2

menu-0-0 = Internet
menu-0-1 = Files
menu-0-2 = Terminal
menu-0-0-exec = menu-open-1
menu-1-0 =  Google
menu-1-0-exec = firefox google.com &
