[colors.breeze] # dim colors
background = '#232627'
foreground = '#fcfcfc'
black =   '#31363b'
red =     '#783228'
green =   '#17a262'
yellow =  '#b65619'
blue =    '#1b668f'
magenta = '#614a73'
cyan =    '#186c60'
white =   '#63686d'

[colors.nord]
background = '#2E3440'
foreground = '#D8DEE9'
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

[colors.ashes]
background = '#1c2023'
foreground = '#c7ccd1'
black   = '#747c84'
red     = '#c7ae95'
green   = '#95c7ae'
yellow  = '#aec795'
blue    = '#ae95c7'
magenta = '#c795ae'
cyan    = '#95aec7'
white   = '#c7ccd1'

[colors.solarized]
background = '#002b36'
foreground = '#839496'
black   = '#002b36'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#6c71c4'
cyan    = '#2aa198'
white   = '#eee8d5'

[colors.gnome]
background = '#1e1e1e'
foreground = '#ffffff'
black   = '#171421'
red     = '#c01c28'
green   = '#26a269'
yellow  = '#a2734c'
blue    = '#12488b'
magenta = '#a347ba'
cyan    = '#2aa1b3'
white   = '#d0cfcc'

[colors.darkfalcon]
background = '#020221'
foreground = '#b4b4b9'
black   = '#000004'
red     = '#ff3600'
green   = '#718e3f'
yellow  = '#ffc552'
blue    = '#635196'
magenta = '#ff761a'
cyan    = '#34bfa4'
white   = '#b4b4b9'

[colors.brightfalcon]
background = '#020221'
foreground = '#b4b4b9'
black   = '#020221'
red     = '#ff8e78'
green   = '#b1bf75'
yellow  = '#ffd392'
blue    = '#99a4bc'
magenta = '#ffb07b'
cyan    = '#8bccbf'
white   = '#f8f8ff'

[colors.tokyo-night]
background = '#24283b'
foreground = '#a9b1d6'
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#9699a8'
