[colors.primary]
background = '#1d1f12'
foreground = '#c5c8c6'

[colors.normal]
black = 		'#212121'
red =			'#cc342b'
green = 		'#198844'
yellow = 	'#fba922'
blue =		'#3971ed'
magenta = 	'#a36ac7'
cyan = 		'#24c1e0'
white = 		'#c5c8c6'

[colors.bright]
black = 		'#969896'
red =			'#cc342b'
green = 		'#198844'
yellow = 	'#fba922'
blue =		'#3971ed'
magenta = 	'#a36ac7'
cyan = 		'#24c1e0'
white = 		'#ffffff'
