"colors": {
    "editor.background": "#ffffff",
    "editor.foreground": "#000000",
    "editor.lineHighlightBackground": "#F5F5F5",
    "editorIndentGuide.activeBackground": "#D2D2D2",
    "editorIndentGuide.background": "#E3E4E4",
    "editorLineNumber.foreground": "#929292",
    "editorLineNumber.background": "#e4e4e4",
    "editorBracketMatch.background": "#f1f8ff",
    "editorBracketMatch.border": "#c8e1ff",
    "editorGroupHeader.tabsBackground": "#EAEAEA",
    "editorGroupHeader.tabsBorder": "#D2D2D2",
    "editorGroup.border": "#a09ea0",
    "editorGroupHeader.border": "#C3C3C3",
    "tab.activeBackground": "#F9F9F9",
    "tab.activeForeground": "#474747",
    "tab.activeBorder": "#DADADA",
    "tab.activeBorderTop": "#FFFFFF",
    "tab.inactiveBackground": "#ECECEC",
    "tab.inactiveForeground": "#6D6D6D",
    "tab.border": "#D2D2D2",
    "statusBar.background": "#F5F6F6",
    "statusBar.foreground": "#494949",
    "statusBar.noFolderForeground": "#575557",
    "statusBar.noFolderBackground": "#ededed",
    "statusBar.border": "#DCDBDA",
    "statusBar.debuggingBackground": "#fafbfc",
    "statusBar.debuggingForeground": "#24292e",
    "activityBar.background": "#ECECEC",
    "activityBar.border": "#D8D8D8",
    "activityBar.foreground": "#6A6A69",
    "activityBar.inactiveForeground": "#6A6A69",
    "activityBarBadge.background": "#FFFFFF",
    "activityBarBadge.foreground": "#575557",
    "sideBar.background": "#EAEAEA",
    "sideBar.foreground": "#464646",
    "sideBar.border": "#D2D2D2",
    "sidebarTitle.background": "#f6f6f6",
    "sideBarTitle.foreground": "#575557",
    "sideBarSectionHeader.background": "#f6f6f6",
    "sideBarSectionHeader.foreground": "#808080",
    "sideBarSectionHeader.border": "#d5d5d5",
    "list.hoverBackground": "#D0D0D0",
    "list.hoverForeground": "#262426",
    "list.activeSelectionBackground": "#0069d9",
    "list.activeSelectionForeground": "#ffffff",
    "list.inactiveSelectionBackground": "#0069d9",
    "list.inactiveSelectionForeground": "#ffffff",
    "list.focusHighlightForeground": "#9dddff",
    "titlebar.inactiveForeground": "#E0E0E0",
    "titleBar.activeBackground": "#FDFDFD",
    "titleBar.border": "#D2D2D2",
    "panel.background": "#F9F9F9",
    "panel.border": "#DCDBDA",
    "panelInput.border": "#DCDBDA",
    "panelTitle.activeBorder": "#101010",
    "panelTitle.activeForeground": "#24292e",
    "input.background": "#ffffff",
    "input.foreground": "#262426",
    "input.border": "#e0e0e0",
    "inputOption.activeBackground": "#e0e0e0",
    "focusBorder": "#eeeeee",
    "dropdown.background": "#ffffff",
    "dropdown.border": "#c4c4c4",
    "dropdown.foreground": "#262426",
    "scrollbarSlider.background": "#CACACA",
    "scrollbarSlider.hoverBackground": "#C0C0C0",
    "scrollbarSlider.activeBackground": "#C0C0C0",
    "scrollbar.shadow": "#f0f0f0",
    "editorCursor.foreground": "#101010",
    "editor.wordHighlightBackground": "#DFEDFF",
    "terminal.ansiBlue": "#282BFF",
    "terminal.ansiBrightBlue": "#272BFF",
    "terminal.ansiCyan": "#0B0098",
    "terminal.ansiBrightCyan": "#301CAE",
    "terminal.ansiGreen": "#277F2B",
    "terminal.ansiBrightGreen": "#449444",
    "terminal.ansiMagenta": "#AE30C2",
    "terminal.ansiBrightMagenta": "#BA3DCA",
    "terminal.ansiRed": "#C71211",
    "terminal.ansiBrightRed": "#D9564E",
    "terminal.ansiWhite": "#ffffff",
    "terminal.ansiBrightWhite": "#eeeeee",
    "editorWidget.background": "#EAEAEA",
    "editorWidget.border": "#eaeaea",
    "button.secondaryBackground": "#505050",
    "button.secondaryHoverBackground": "#505050",
    "button.border": "#EAEAEA",
    "button.background": "#1f6ae2",
    "button.hoverBackground": "#1f6ae2",
    "widget.shadow": "#cecece",
    "widget.border": "#cfcfcf",
    "notificationCenterHeader.background": "#f7f7f7",
    "notifications.border": "#e5e5e6",
    "notification.background": "#54a3ff",
    "editorSuggestWidget.background": "#FBFBFB",
    "editorSuggestWidget.selectedBackground": "#0069D9",
    "editorSuggestWidget.selectedForeground": "#FFFFFF",
    "editorSuggestWidget.highlightForeground": "#0069D9",
    "editorSuggestWidget.border": "#E0E0E0",
    "editorHoverWidget.background": "#FBFBFB",
    "editorHoverWidget.selectedBackground": "#0069D9",
    "editorHoverWidget.border": "#E0E0E0",
