#▓██   ██▓ ▄▄▄       ███▄ ▄███▓ ▄▄▄▄    ▄▄▄       ██▀███  
# ▒██  ██▒▒████▄    ▓██▒▀█▀ ██▒▓█████▄ ▒████▄    ▓██ ▒ ██▒
#  ▒██ ██░▒██  ▀█▄  ▓██    ▓██░▒██▒ ▄██▒██  ▀█▄  ▓██ ░▄█ ▒
#  ░ ▐██▓░░██▄▄▄▄██ ▒██    ▒██ ▒██░█▀  ░██▄▄▄▄██ ▒██▀▀█▄  
#  ░ ██▒▓░ ▓█   ▓██▒▒██▒   ░██▒░▓█  ▀█▓ ▓█   ▓██▒░██▓ ▒██▒
#   ██▒▒▒  ▒▒   ▓▒█░░ ▒░   ░  ░░▒▓███▀▒ ▒▒   ▓▒█░░ ▒▓ ░▒▓░
# ▓██ ░▒░   ▒   ▒▒ ░░  ░      ░▒░▒   ░   ▒   ▒▒ ░  ░▒ ░ ▒░
# ▒ ▒ ░░    ░   ▒   ░      ░    ░    ░   ░   ▒     ░░   ░ 
# ░ ░           ░  ░       ░    ░ by nichtgestalt   ░   ░     
# ░ ░                                ░                    


hack: &hack HackNerdFont:pixelsize=16
inconsolata: &inconsolata InconsolataNerdFont:pixelsize=16
iosevka: &iosevka IosevkaNerdFont:pixelsize=16
jetbrains: &jetbrains JetBrainsMonoNerdFont:pixelsize=16
fira: &fira FiraCodeNerdFont:pixelsize=16
sauce: &sauce SauseCodeProNerdFont:pixelsize=16
space: &space SpaceMonoNerdFont:pixelsize=16
shure: &shure ShureTechMonoNerdFont:pixelsize=16
roboto: &roboto RobotoMonoNerdFont:pixelsize=16
cantarell: &cantarell Cantarell:pixelsize=17

# colors
bg: &bg 232627ff   # background
fg: &fg eff0f1ff   # foreground
hl: &hl 614a73ff   # highlight
dim: &dim 7f8c8dff # dim foreground
ac: &ac 3daee9ff   # accent color
#ac: &ac 16a085ff   # accent color
mrg: &mrg 14
bar:
  height: 24
  location: top
  font: *hack
  layer: bottom
  foreground: *fg
  background: *bg

####
  left:
    - label:
        content: 
          string: 
              text: " "
              font: hack HackNerdFont:pixelsize=25
              margin: 20
              foreground: fdbc4bff
              on-click:
                left: sh -c "pkill rofi || rofi -show drun"
                right: sh -c "pkill rofi || powermenu"
                middle: sh -c "musicfinder --music"
                wheel-up: sh -c "picker hex"
                wheel-down: sh -c "picker hsl"
    - river:
        anchors:
          - base: &river_base
              left-margin: 5
              right-margin: 5 
              default: {string: {text:  }}
              font: HackNerdFont:pixelsize=11
              foreground: *dim
              conditions:
                id == 1: {string: {text:  }}  
                id == 2: {string: {text:  }}  
                id == 3: {string: {text:  }}  
                id == 4: {string: {text:  }}  
                id == 5: {string: {text:  }}  
                id == 6: {string: {text:  }}  
                id == 7: {string: {text:  }}  
                id == 8: {string: {text:  }}  
                id == 9: {string: {text: '*' }}  
        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            right-margin: 6
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == focused:
                map:
                  <<: *river_base
                  conditions:
                    #id == 1: {string: {text:  , foreground: *hl}}  
                    id == 1: {string: {text:  }}  
                    id == 2: {string: {text:  }}  
                    id == 3: {string: {text:  }}  
                    id == 4: {string: {text:  }}  
                    id == 5: {string: {text:  }}  
                    id == 6: {string: {text:  }}  
                    id == 7: {string: {text:  }}  
                    id == 8: {string: {text:  }}  
                    id == 9: {string: {text: '*' }}  
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
#### 
  center:    
    - script:
        poll-interval: 1000
        path: /home/ghost/.local/bin/mpbar
        content:
          - string:
              text: " {prefix} "
              foreground: *ac
              on-click:
                left: 
                right:  "playerctl -p mpv position 120-"
                middle: 
                wheel-up: "playerctl -p mpv position 5+" 
                wheel-down: "playerctl -p mpv position 5-" 
          - string:
              text: "{title} {position}"
              foreground: *dim
              on-click:
                left: "playerctl -p mpv play-pause"
                right: "notify-send 'Playing:' '{title} {totallength}'"
                middle: 
                wheel-up: "playerctl -p mpv volume 0.1+"
                wheel-down: "playerctl -p mpv volume 0.1-"
          - string:
              text: " {suffix} "
              foreground: *ac
              on-click:
                left: 
                right: "playerctl -p mpv position 120+"
                middle: 
                wheel-up: "playerctl -p mpv position 5+"
                wheel-down: "playerctl -p mpv position 5-" 
####
  right:
    - script:
        poll-interval: 1000
        path: /home/ghost/.local/bin/pombar
        content:
          - string:
              text: "{prefix}"
              foreground: *fg
              left-margin: 0
              on-click:
                left: "countdown 1500"
                right: sh -c "pkill countdown && rm /home/ghost/.local/cache/remaining_time.txt"
          - string:
              text: "{time}"
              foreground: *dim
              right-margin: *mrg

    - label:
        content: 
          string: 
              text: "󱅅"
              font: *hack
              margin: *mrg
              foreground: *fg
              on-click:
                left: sh -c "pkill rofi || bar_wp_menu"
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                - string: 
                    text: "󰕾" 
                    foreground: *fg
                    margin: *mrg
                    on-click:
                      wheel-up: sh -c "$HOME/.local/bin/vol_wob --up-1"
                      wheel-down:  sh -c "$HOME/.local/bin/vol_wob --down-1"
                      left: sh -c 'notify-send "Volume" "$(cat $HOME/.cache/wob/vol.wob)"'
    - clock:
        date-format: "%e.%b"
        time-format: "%H:%M"
        content:
          - string: 
              text: "{date} {time}" 
              foreground: *dim
              margin: *mrg
              font: *hack
