# Y A M B A R
import: ~/.config/yambar/test.yml
hack: &hack Hack Nerd Font:pixelsize=16
time: &time Hack Nerd Font:pixelsize=15
bg_default: &bg_default {stack: [{background: {color: 1b668fff}}, ]}
bar:
  height: 24
  location: top
  font: *hack
  layer: bottom
  foreground: fcfcfcff
  background: 232627ff

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 9 
              default: {string: {text: , font: *hack}}
              conditions:
                id == 1: {string: {text: 1, font: *hack}}  
                id == 2: {string: {text: 2, font: *hack}}  
                id == 3: {string: {text: 3, font: *hack}}  
                id == 4: {string: {text: 4, font: *hack}}  
                id == 5: {string: {text: 5, font: *hack}}  
                id == 10: {string: {text: "scratchpad", font: *hack}}  
                id == 11: {string: {text: "work", font: *hack}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                    #deco: {underline: {size: 3, color: ea6962ff}}
  center:
    - clock:
        time-format: "%H:%M"
        date-format: "%e.%b"
        content:
          - string: {text: "{date}", font: *time, margin: 5}
          - string: {text: "{time}", font: *time, margin: 5}

  right:
    - mem:
        poll-interval: 2500
        content:
          - string: {text: "[  {percent_used}%]", foreground: 11d116ff, margin: 5}
    - cpu:
        poll-interval: 5000
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "[  {cpu}%]", foreground: f67400ff, margin: 5}
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                - string: {text: "[󰕾 {cubic_volume}%]", foreground: 3daee9ff , margin: 5}
    #- battery:
        #name: BAT0
        #poll-interval: 180000
        #content:
          #- string: {text: "[󰁹 {capacity}%]", foreground: 1cdc9aff, margin: 5}
    #- backlight:
        #name: intel_backlight
        #content: 
          #- string: {text: "[󰌵 {percent}%]", foreground: fdbc4bff, margin: 5}

