#▓██   ██▓ ▄▄▄       ███▄ ▄███▓ ▄▄▄▄    ▄▄▄       ██▀███  
# ▒██  ██▒▒████▄    ▓██▒▀█▀ ██▒▓█████▄ ▒████▄    ▓██ ▒ ██▒
#  ▒██ ██░▒██  ▀█▄  ▓██    ▓██░▒██▒ ▄██▒██  ▀█▄  ▓██ ░▄█ ▒
#  ░ ▐██▓░░██▄▄▄▄██ ▒██    ▒██ ▒██░█▀  ░██▄▄▄▄██ ▒██▀▀█▄  
#  ░ ██▒▓░ ▓█   ▓██▒▒██▒   ░██▒░▓█  ▀█▓ ▓█   ▓██▒░██▓ ▒██▒
#   ██▒▒▒  ▒▒   ▓▒█░░ ▒░   ░  ░░▒▓███▀▒ ▒▒   ▓▒█░░ ▒▓ ░▒▓░
# ▓██ ░▒░   ▒   ▒▒ ░░  ░      ░▒░▒   ░   ▒   ▒▒ ░  ░▒ ░ ▒░
# ▒ ▒ ░░    ░   ▒   ░      ░    ░    ░   ░   ▒     ░░   ░ 
# ░ ░           ░  ░       ░    ░ by nichtgestalt   ░   ░     
# ░ ░                                ░                    


hack: &hack Hack Nerd Font:pixelsize=16
inconsolata: &inconsolata InconsolataNerdFont:pixelsize=16
iosevka: &iosevka IosevkaNerdFont:pixelsize=16
jetbrains: &jetbrains JetBrainsMonoNerdFont:pixelsize=16
fira: &fira FiraCodeNerdFont:pixelsize=16
sauce: &sauce SauseCodeProNerdFont:pixelsize=16
space: &space SpaceMonoNerdFont:pixelsize=16
shure: &shure ShureTechMonoNerdFont:pixelsize=16
roboto: &roboto RobotoMonoNerdFont:pixelsize=16

bg: &bg bcd7ddff
fg: &fg 1f1f1fff
hl: &hl 4dbdeeff
mrg: &mrg 10
bar:
  height: 24
  location: top
  font: *hack
  layer: bottom
  foreground: *fg
  background: *bg

####
  left:
    - label:
        content: 
          string: 
              text: " "
              margin: 10
              on-click:
                left: sh -c "pkill rofi || rofi -show drun"
                right: sh -c "pkill rofi || powermenu"
                middle: sh -c "footclient -e nvim ~/.config/yambar/colors.rasi"
                wheel-up: sh -c "picker hex"
                wheel-down: sh -c "picker hsl"
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 9 
              default: {string: {text:  }}
              conditions:
                id == 1: {string: {text: 1 }}  
                id == 2: {string: {text: 2 }}  
                id == 3: {string: {text: 3 }}  
                id == 4: {string: {text: 4 }}  
                id == 5: {string: {text: 5 }}  
                id == 10: {string: {text: "scratchpad" }}  
                id == 11: {string: {text: "work" }}  
        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == focused:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                    #deco: {underline: {size: 3, color: ea6962ff}}
    #- foreign-toplevel:
        #content:
          #map:
            #conditions:
              #~activated: {empty: {}}
              #activated:
              #string: 
                #text: "{app-id}"
                #margin: 15
####
  center:
    - clock:
        date-format: "%e.%b"
        content:
          string: 
            text: "{date}" 
            margin: 5
            on-click:
              left: 
              right: 
              middle: 
              wheel-up:
              wheel-down:
    - clock:
        time-format: "%H:%M"
        content:
          string:
            text: "{time}"
            margin: 5
            on-click:
              left: 
              right: 
              middle: 
              wheel-up:
              wheel-down:
####
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                string: 
                    text: "[󰕾 {cubic_volume}%]" 
                    foreground: *fg
                    margin: *mrg
                    on-click:
                      wheel-up: sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"
                      wheel-down:  sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"
    - cpu:
        poll-interval: 5000
        content:
          map:
            conditions:
              id < 0:
                string: 
                    text: "[  {cpu}%]" 
                    foreground: *fg
                    margin: *mrg
    - mem:
        poll-interval: 2500
        content:
          string: 
              text: "[  {percent_used}%]" 
              foreground: *fg
              margin: *mrg
    #- battery:
        #name: BAT0
        #poll-interval: 180000
        #content:
          #- string: {text: "[󰁹 {capacity}%]", foreground: 1cdc9aff, margin: 5}
    #- backlight:
        #name: intel_backlight
        #content: 
          #- string: {text: "[󰌵 {percent}%]", foreground: fdbc4bff, margin: 5}

