#▓██   ██▓ ▄▄▄       ███▄ ▄███▓ ▄▄▄▄    ▄▄▄       ██▀███  
# ▒██  ██▒▒████▄    ▓██▒▀█▀ ██▒▓█████▄ ▒████▄    ▓██ ▒ ██▒
#  ▒██ ██░▒██  ▀█▄  ▓██    ▓██░▒██▒ ▄██▒██  ▀█▄  ▓██ ░▄█ ▒
#  ░ ▐██▓░░██▄▄▄▄██ ▒██    ▒██ ▒██░█▀  ░██▄▄▄▄██ ▒██▀▀█▄  
#  ░ ██▒▓░ ▓█   ▓██▒▒██▒   ░██▒░▓█  ▀█▓ ▓█   ▓██▒░██▓ ▒██▒
#   ██▒▒▒  ▒▒   ▓▒█░░ ▒░   ░  ░░▒▓███▀▒ ▒▒   ▓▒█░░ ▒▓ ░▒▓░
# ▓██ ░▒░   ▒   ▒▒ ░░  ░      ░▒░▒   ░   ▒   ▒▒ ░  ░▒ ░ ▒░
# ▒ ▒ ░░    ░   ▒   ░      ░    ░    ░   ░   ▒     ░░   ░ 
# ░ ░           ░  ░       ░    ░ by nichtgestalt   ░   ░     
# ░ ░                                ░                    

# fonts
hack: &hack HackNerdFont:pixelsize=16
inconsolata: &inconsolata InconsolataNerdFont:pixelsize=16
iosevka: &iosevka IosevkaNerdFont:pixelsize=16
jetbrains: &jetbrains JetBrainsMonoNerdFont:pixelsize=16
fira: &fira FiraCodeNerdFont:pixelsize=16
sauce: &sauce SauseCodeProNerdFont:pixelsize=16
space: &space SpaceMonoNerdFont:pixelsize=16
shure: &shure ShureTechMonoNerdFont:pixelsize=16
roboto: &roboto RobotoMonoNerdFont:pixelsize=16
cantarell: &cantarell Cantarell:pixelsize=17

# colors
bg: &bg 232627ff   # background
fg: &fg eff0f1ff   # foreground
hl: &hl 614a73ff   # highlight
mrg: &mrg 8       # margin
bar:
  height: 24
  location: top
  font: *hack
  layer: bottom
  foreground: *fg
  background: *bg

####
  left:
    - label:
        content: 
          string: 
              text: " "
              margin: 10
              foreground: *fg
              on-click:
                left: sh -c "pkill rofi || rofi -show drun"
                right: sh -c "pkill rofi || powermenu"
                middle: sh -c "footclient -e nvim ~/.config/yambar/colors.rasi"
                wheel-up: sh -c "picker hex"
                wheel-down: sh -c "picker hsl"
    - river:
        anchors:
          - base: &river_base
              left-margin: 5
              right-margin: 5 
              default: {string: {text:  }}
              font: HackNerdFont:pixelsize=12
              conditions:
                id == 1: {string: {text:  }}  
                id == 2: {string: {text:  }}  
                id == 3: {string: {text:  }}  
                id == 4: {string: {text:  }}  
                id == 5: {string: {text:  }}  
                id == 6: {string: {text:  }}  
                id == 7: {string: {text:  }}  
                id == 8: {string: {text:  }}  
                id == 9: {string: {text: '*' }}  
        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            right-margin: 6
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == focused:
                map:
                  <<: *river_base
                  #deco: {background: {color: *hl }}
                  conditions:
                    #id == 1: {string: {text:  , foreground: *hl}}  
                    id == 1: {string: {text:  }}  
                    id == 2: {string: {text:  }}  
                    id == 3: {string: {text:  }}  
                    id == 4: {string: {text:  }}  
                    id == 5: {string: {text:  }}  
                    id == 6: {string: {text:  }}  
                    id == 7: {string: {text:  }}  
                    id == 8: {string: {text:  }}  
                    id == 9: {string: {text: '*' }}  
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: *hl }}
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  #deco: {underline: {size: 3, color: ea6962ff}}
    #- foreign-toplevel:
        #content:
          #map:
            #conditions:
              #~activated: {empty: {}}
              #activated:
              #string: 
                #text: "{app-id}"
                #margin: 15
    #- script:
    #    path: /home/ghost/.local/bin/yambar-string-wrapper
    #    args: ["alcolor", "--print"]
    #    content:
    #      string:
    #        text: "{stdout}"
####
  center:    
    - clock:
        date-format: "%e.%b"
        content:
          string: 
            text: "{date}" 
            foreground: *fg 
            margin: 0
            font: *hack
            on-click:
              left: 
              right: 
              middle: 
              wheel-up:
              wheel-down:
    - clock:
        time-format: "%H:%M"
        content:
          string:
            text: "{time}"
            foreground: *fg 
            margin: *mrg
            font: *hack
            on-click:
              left: 
              right: 
              middle: 
              wheel-up:
              wheel-down:
    - mpd:
        host: /run/mpd/socket
        content:
          string:
            text: "{title}"
    #- script:
    #    poll-interval: 1000
    #    path: /home/ghost/.local/bin/alcolor
    #    args: ["--yambar"]
    #    content:
    #      string:
    #        text: "{theme}"
####
  right:
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                string: 
                    text: "[󰕾 {cubic_volume}%]" 
                    foreground: 3daee9ff
                    margin: *mrg
                    on-click:
                      wheel-up: sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"
                      wheel-down:  sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"
    - cpu:
        poll-interval: 5000
        content:
          map:
            conditions:
              id < 0:
                string: 
                    text: "[  {cpu}%]" 
                    foreground: fdbc4bff
                    margin: *mrg
    - mem:
        poll-interval: 2500
        content:
          string: 
              text: "[  {percent_used}%]" 
              foreground: 1cdc9aff
              margin: *mrg
            #- battery:
        #name: BAT0
        #poll-interval: 180000
        #content:
          #- string: {text: "[󰁹 {capacity}%]", foreground: 1cdc9aff, margin: 5}
    #- backlight:
        #name: intel_backlight
        #content: 
          #- string: {text: "[󰌵 {percent}%]", foreground: fdbc4bff, margin: 5}

