#!/bin/sh

#pkill yambar
#yambar 

#pgrep yambar && pkill yambar || yambar

case $1 in
   '--toggle')
      pgrep yambar && pkill yambar || yambar & ;;
   '--reload')
      pkill yambar && yambar || yambar & ;;
esac
