#!/bin/sh
#       _                
#  _ __(_)_   _____ _ __ 
# | '__| \ \ / / _ \ '__|
# | |  | |\ V /  __/ |   
# |_|  |_| \_/ \___|_| 
#          ~by nichtgestalt

# autostart
pipewire &
sleep 1 && whybar &
dunst &
foot --server &

# set wallpaper
swaybg -i ~/.config/swayimg/wallpaper &

# set keyboard to de neo
riverctl keyboard-layout -variant neo de

# launch terminal
riverctl map normal Super Return spawn footclient

# application launcher
riverctl map normal Super Space spawn "rofi -show drun"

# bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# close the focused view
riverctl map normal Super X close

# reload waybar
riverctl map normal Super+Shift B spawn whybar

# launch browser
riverctl map normal Super+Shift I spawn firefox

# write tagesplaner
riverctl map normal Super A spawn "footclient -e tagesplaner"

# wallpaper selection
riverctl map normal Super+Shift V spawn "swayimg ~/media/bilder/wallpaper/*"

# read tagesplaner
riverctl map normal Super+Shift A spawn planselector

# launch powermenu
riverctl map normal Super F4 spawn powermenu
#riverctl map normal Super+Shift E exit

# scroll through focused window
riverctl map normal Super R focus-view next
riverctl map normal Super G focus-view previous

# swap focus in layout stack
riverctl map normal Super+Shift R swap next
riverctl map normal Super+Shift G swap previous

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super N send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super T send-layout-cmd rivertile "main-ratio +0.05"

# volume keys
riverctl map normal Super Up spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map normal Super F8 spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map normal Super Down spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal Super F7 spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal Super F6 spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

# toggle float
riverctl map normal Super V toggle-float

# toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# set background and borders
riverctl background-color 0x2e3440
riverctl border-color-focused 0xbcd7dd
riverctl border-color-unfocused 0x586e75
riverctl border-width 1

# set keyboard repeat rate
riverctl set-repeat 40 300

# make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl float-filter-add app-id 'swayimg'
riverctl float-filter-add app-id 'vlc'

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift N send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift T send-layout-cmd rivertile "main-count -1"

# move views
riverctl map normal Super+Alt G move up 50
riverctl map normal Super+Alt R move down 50
riverctl map normal Super+Alt N move left 50
riverctl map normal Super+Alt T move right 50

# snap views to screen edges
riverctl map normal Super+Alt+Control N snap left
riverctl map normal Super+Alt+Control R snap down
riverctl map normal Super+Alt+Control G snap up
riverctl map normal Super+Alt+Control T snap right

# resize views
riverctl map normal Super+Alt+Shift N resize horizontal -100
riverctl map normal Super+Alt+Shift R resize vertical 100
riverctl map normal Super+Alt+Shift G resize vertical -100
riverctl map normal Super+Alt+Shift T resize horizontal 100

# mouse buttons
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# focusing tags
for i in $(seq 1 9)
do
   tags=$((1 << ($i - 1)))
   # Super+[1-9] to focus tag [0-8]
   riverctl map normal Super $i set-focused-tags $tags
   # Super+Shift+[1-9] to tag focused view with tag [0-8]
   riverctl map normal Super+Shift $i set-view-tags $tags
   # Super+Control+[1-9] to toggle focus of tag [0-8]
   riverctl map normal Super+Control $i toggle-focused-tags $tags
   # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
   riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# focusing tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags # focus all tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags # tag focused view with all tags

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
   # Eject the optical drive (well if you still have one that is)
   riverctl map $mode None XF86Eject spawn 'eject -T'

   # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
   riverctl map $mode None XF86AudioRaiseVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
   riverctl map $mode None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
   riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

   # Control screen backlight brightness with light (https://github.com/haikarainen/light)
   riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
   riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'

   # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
   riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
   riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

done

#sleep 5 whybar

# send the focused view to the next/previous output
#riverctl map normal Super+Shift Period send-to-output next
#riverctl map normal Super+Shift Comma send-to-output previous

# change layout orientation
#riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
#riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
#riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
#riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
#riverctl map passthrough Super F11 enter-mode normal
