#!/bin/sh
#       _                
#  _ __(_)_   _____ _ __ 
# | '__| \ \ / / _ \ '__|
# | |  | |\ V /  __/ |   
# |_|  |_| \_/ \___|_| 
#          ~by nichtgestalt

#Terminal=alacritty
#Browser=firefox-wayland

# autostart
pipewire &
dunst &

# set background
wbg $HOME/.config/imv/wallpaper &
#swaybg -m fill -i ~/.config/imv/wallpaper &
#riverctl background-color 0x12488b
#riverctl background-color 0x008080 # windows teal

# set keyboard to de neo
riverctl keyboard-layout -variant neo de

# set keyboard repeat rate
riverctl set-repeat 40 300

# launch terminal
riverctl map normal Super Return spawn "$TERM"
riverctl map normal Control+Shift Return spawn "$TERM -e yash -l"

# application launcher
riverctl map normal Super Space spawn "pkill rofi || rofi -show drun"

# bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# close the focused view
riverctl map normal Super X close

# reload and toggle waybar
riverctl map normal Super+Shift B spawn "whybar --reload"
riverctl map normal Super F2 spawn "whybar --toggle"

# set mouse cursor
riverctl xcursor-theme Adwaita

# toggle float
riverctl map normal Super V toggle-float

# wallpaper selection
riverctl map normal Super+Shift V spawn 'wallpaperset --all'
riverctl map normal Super+Alt V spawn 'wallpaperset --category'

# toggle fullscreen
riverctl map normal Super L toggle-fullscreen

# theme picker
riverctl map normal Super U spawn 'pkill rofi || alcolor --open'
#riverctl map normal Super+Shift U spawn 'pkill rofi || alcolor --set'

# colorpicker
riverctl map normal Super P spawn 'colorpicker --hex'

# write and read tagesplaner
riverctl map normal Super A spawn '$TERM -e adeptus'
riverctl map normal Super+Shift A spawn '$TERM -e nvim ~/media/office/onyx/tagesthemen.md'

# launch browser
riverctl map normal Super I spawn '$BROWSER'
riverctl map normal Control+Shift I spawn 'firefox --private-window'

# onyx
riverctl map normal Control F spawn '$TERM -e onyx'

# musicfinder
riverctl map normal Super Q spawn "pkill rofi || musicfinder --media-dir"
riverctl map normal Super+Shift Q spawn "pkill rofi || musicfinder --live-wallpaper"
riverctl map normal Super+Control Q spawn "pkill rofi || musicfinder --thumbnail"

# color images
riverctl map normal Super S spawn 'ls -t $HOME/.cache/colors.d/ | head -n1 | xargs -I {} swappy -f $HOME/.cache/colors.d/{}'
riverctl map normal Super+Shift S spawn 'pkill rofi || ls -t $HOME/.cache/colors.d/ | rofi -dmenu -p "Select color images" | xargs -I {} swappy -f $HOME/.cache/colors.d/{}'

# emoji-picker
riverctl map normal Super M spawn 'pkill rofi || emoji-picker --emoji'
riverctl map normal Super+Shift M spawn 'pkill rofi || emoji-picker --nerd-font'

## function keys
# pipewire
riverctl map normal Super F8 spawn		'vol_wob --up-5'
riverctl map normal Super F7 spawn		'vol_wob --down-5'
riverctl map normal Super F6 spawn		'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

# control mpv
riverctl map normal Control F6 spawn 	'notify-send "Volume $(playerctl -p mpv volume)"'
riverctl map normal Control F7 spawn 	'playerctl -p mpv volume 0.1-'
riverctl map normal Control F8 spawn	'playerctl -p mpv volume 0.1+'

riverctl map normal Control F9 spawn        	'playerctl -p mpv previous && notify-send "$(playerctl -p mpv metadata title)"'
riverctl map normal Control+Shift F9 spawn	'playerctl -p mpv position 5-'
riverctl map normal Control F10 spawn      	'playerctl -p mpv play-pause'
riverctl map normal Control+Shift F10 spawn 	'notify-send "Currently Playing:" "$(playerctl -p mpv metadata title)"'

riverctl map normal Control F11 spawn			'playerctl -p mpv next && notify-send "Currently Playing:" "$(playerctl -p mpv metadata title)"'
riverctl map normal Control+Shift F9 spawn	'playerctl -p mpv position 5+'
riverctl map normal Control F12 spawn       	'pkill mpv'

# screenshots
riverctl map normal Super F12 spawn 'wlscreenshot'

# close rofi
#riverctl map normal Super F1 spawn 'pkill rofi'

# launch powermenu
riverctl map normal Super F4 spawn powermenu

# bookmarking
riverctl map normal Super F5 spawn 'notify-send "F5: copy url to:" "Bookmarks:\tSuper+Shift\nVideo file:\t\tCtrl+Shift F5"'
riverctl map normal Super+Shift F5 spawn 'sitemarker'
riverctl map normal Control+Shift F5 spawn 'videomarker'

## window management
# scroll through focused window
riverctl map normal Super R focus-view next
riverctl map normal Super G focus-view previous

# swap focus in layout stack
riverctl map normal Super+Shift R swap next
riverctl map normal Super+Shift G swap previous

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super N send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super T send-layout-cmd rivertile "main-ratio +0.05"

# floating by default - use lswt to get app-id
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl float-filter-add app-id 'imv'
riverctl float-filter-add app-id 'vlc'
riverctl float-filter-add app-id 'mpv'
riverctl float-filter-add app-id 'Gimp'

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# server side decorations
riverctl rule-add -app-id Firefox ssd
riverctl rule-add -app-id thunar ssd
riverctl rule-add -app-id imv ssd
riverctl rule-add -app-id nwg-look ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.5 &
# rivertile -outer-padding 6 -view-padding 6 -main-ratio 0.5 -main-location top &

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift N send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift T send-layout-cmd rivertile "main-count -1"

# change layout orientation
#riverctl map normal Control+Shift G send-layout-cmd rivertile "main-location top"
#riverctl map normal Control+Shift T send-layout-cmd rivertile "main-location right"
#riverctl map normal Control+Shift R send-layout-cmd rivertile "main-location bottom"
#riverctl map normal Control+Shift T send-layout-cmd rivertile "main-location left"

# move views
riverctl map normal Super+Alt G move up 50
riverctl map normal Super+Alt R move down 50
riverctl map normal Super+Alt N move left 50
riverctl map normal Super+Alt T move right 50

# snap views to screen edges
riverctl map normal Super+Alt+Control N snap left
riverctl map normal Super+Alt+Control R snap down
riverctl map normal Super+Alt+Control G snap up
riverctl map normal Super+Alt+Control T snap right

# resize views
riverctl map normal Super+Alt+Shift N resize horizontal -100
riverctl map normal Super+Alt+Shift R resize vertical 100
riverctl map normal Super+Alt+Shift G resize vertical -100
riverctl map normal Super+Alt+Shift T resize horizontal 100

# set borders
riverctl border-color-focused 0x7f8c8d
riverctl border-color-unfocused 0x282c34
riverctl border-width 1

# mouse buttons
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# focusing tags
for i in $(seq 1 9)
do
   tags=$((1 << ($i - 1)))
   # Super+[1-9] to focus tag [0-8]
   riverctl map normal Super $i set-focused-tags $tags
   # Super+Shift+[1-9] to tag focused view with tag [0-8]
   riverctl map normal Super+Shift $i set-view-tags $tags
   # Super+Control+[1-9] to toggle focus of tag [0-8]
   riverctl map normal Super+Control $i toggle-focused-tags $tags
   # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
   riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# focusing tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags # focus all tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags # tag focused view with all tags

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
   # Eject the optical drive (well if you still have one that is)
   riverctl map $mode None XF86Eject spawn 'eject -T'

   # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
   riverctl map $mode None XF86AudioRaiseVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
   riverctl map $mode None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
   riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

   # Control screen backlight brightness with light (https://github.com/haikarainen/light)
   riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
   riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'

   # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
   riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
   riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
   riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

done

# launch bar
sleep 1 && whybar --reload &

# launch xremapeae
pkill xremap
ls ~/.cargo/bin/xremap && xremap ~/.config/xremap/config.yml &

# wob for pipewire
tail -f $HOME/.cache/wob/vol.wob | wob &

# launch lavalauncher
#pkill lavalauncher
#lavalauncher &

# censor beep
#riverctl map normal Super F9 spawn "mpv ~/media/music/censor-beep.mp3"
#riverctl map -release normal Super F9 spawn "pkill mpv"

# Super+Period and Super+Comma to focus the next/previous output
#riverctl map normal Super Period focus-output next
#riverctl map normal Super Comma focus-output previous

# send the focused view to the next/previous output
#riverctl map normal Super+Shift Period send-to-output next
#riverctl map normal Super+Shift Comma send-to-output previous

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
#riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
#riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
#riverctl map passthrough Super F11 enter-mode normal
