#!/bin/sh

sort_func() {
  arr=("$@")
  for ((i = 0; i < ${#arr[@]}; i++)); do
    for ((j = 0; j < ${#arr[@]} - i - 1; j++)); do
      if [ "${arr[j]}" \> "${arr[j+1]}" ]; then
        tmp="${arr[j]}"
        arr[j]="${arr[j+1]}"
        arr[j+1]="$tmp"
      fi
    done
  done
  echo "${arr[@]}"
}
